on:
  workflow_dispatch:
  push:
    branches:
      - dev
name: Build_P
jobs:
  make:
    name: Build and Upload Sileo
    runs-on: macos-12
    steps:
      - uses: actions/cache@v2
        id: procache
        with:
          path: |
            ~/__cache
            /Applications/Xcode_12.4.app/Contents/Developer/Toolchains
          key: ${{ runner.os }}-procursus
          
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: false

      - name: Setup Procursus Bootstrap (install)
        if: steps.procache.outputs.cache-hit != 'true'
        run: |
          wget https://procursus.itsnebula.net/bootstrap_darwin-amd64.tar.zst
          sudo gtar --preserve-permissions -xkf ./bootstrap_darwin-amd64.tar.zst -C /
          echo '/opt/procursus/sbin:/opt/procursus/bin' >> $GITHUB_PATH
          sudo sed -i '' 's/apt.procurs.us/procursus.itsnebula.net/' /opt/procursus/etc/apt/sources.list.d/procursus.sources
          PATH=/opt/procursus/sbin:/opt/procursus/bin:$PATH sudo /opt/procursus/bin/apt update
          sudo /opt/procursus/bin/apt -V dist-upgrade -y || :
          sudo /opt/procursus/bin/apt -V dist-upgrade -y
          sudo /opt/procursus/bin/apt install ldid make -y
          
      - name: Add Procursus to PATH
        run: |
          echo '/opt/procursus/sbin:/opt/procursus/bin' >> $GITHUB_PATH
          
      - name: Setup Procursus Bootstrap (cache)
        if: steps.procache.outputs.cache-hit == 'true'
        run: |
          sudo mkdir -p ~/__cache/procursus/var/cache/apt/archives/partial ~/__cache/procursus/var/lib/apt/lists/partial
          sudo rsync -aP ~/__cache/procursus /opt
          sudo /opt/procursus/bin/apt update
          sudo /opt/procursus/bin/apt -V dist-upgrade -y
          sudo /opt/procursus/bin/apt -V dist-upgrade -y

      - name: Select Correct Xcode (13.1)
        run: |
          sudo xcode-select --switch /Applications/Xcode_13.4.1.app
      - name: Build Sileo Nightly (iphoneos-arm)
        run: |
          gmake clean package NIGHTLY=1 DEBUG=0 ALL_BOOTSTRAPS=1
          
      -  name: Upload to GitHub Artifiacts
         uses: actions/upload-artifact@v2.2.2
         with:
          path: ./packages/*.deb

      - name: Copy Procursus to Cache Location
        run: |
          sudo mkdir -p ~/__cache
          sudo rsync -aP /opt/procursus ~/__cache
          sudo rm -rf ~/__cache/procursus/var/cache/apt/archives/partial ~/__cache/procursus/var/lib/apt/lists/partial ~/__cache/procursus/Library/dpkg/triggers/Lock
